name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
    
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dongshanpiseven-core
          path: |
            README.md
            sdcard.img.gz
            splash.bmp
            stm32mp157c-100ask-512d-hdmi-v1.dtb
            stm32mp157c-100ask-512d-lcd-v1.dtb
            stm32mp157c-100ask-512d-v1.dtb
            tf-a-stm32mp157c-100ask-512d-v1.stm32
            u-boot.stm32
            uImage
            uInitrd
            
      - run: ls -la
      
      - name: ssh deploy
        # You may pin to the exact commit or the version.
        # uses: easingthemes/ssh-deploy@c711f2c3391cac2876bf4c833590077f02e4bcb8
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          # Private Key
          SSH_PRIVATE_KEY: '${{ secrets.SSH_ID_RSA }}'
          # Remote host
          REMOTE_HOST: 222.186.41.113
          # Remote user
          REMOTE_USER: root
          # Remote port
          REMOTE_PORT: 22
          # Source directory
          SOURCE: ./
          # Target directory
          TARGET: /root/test
