name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
    
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dongshanpiseven-core
          path: |
            README.md
            sdcard.img.gz
            splash.bmp
            stm32mp157c-100ask-512d-hdmi-v1.dtb
            stm32mp157c-100ask-512d-lcd-v1.dtb
            stm32mp157c-100ask-512d-v1.dtb
            tf-a-stm32mp157c-100ask-512d-v1.stm32
            u-boot.stm32
            uImage
            uInitrd
            
      - run: ls -la
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
                ls  -la
                cd /root/HomeSite_vuepress/
                pull
