name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release.txt
            README.md
            
      - name: Upload firmware to cowtransfer
        id: cowtransfer
        run: |
         curl -fsSL git.io/file-transfer | sh
         ./transfer cow --cookie="remember-mev2=${REMEMBER_MEV2};" -a "${COW_AUTH_TOKEN}"  README.md 2>&1 | tee cowtransfer.log
         echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
         echo "::set-output name=url::$(cat cowtransfer.log | grep https | cut -f3 -d" ")"
